global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets:
          - "pulsegaurd-api-gateway-1:3001"
          - "pulsegaurd-api-gateway-2:3001"
          - "pulsegaurd-api-gateway-3:3001"
          - "pulsegaurd-api-gateway-4:3001"
          - "pulsegaurd-api-gateway-5:3001"
    metrics_path: /metrics
